### PR TITLE
Overlay

### PR DESCRIPTION
**Pull request by pweigand**
Added option "overlay".
When true it will show a play sign which can be clicked to play the underlaying gif. While playing the sign is hidden. If the gif is clicked, it will stop playing and display the play sign again.

### CODE REVIEW

**Comment by nickforddesign** [comment]
Looks good, it does open a new discussion about maybe making it very easy to customize the play icon. Maybe using base64 svg isn't the most user friendly solution, maybe it's best to include an svg asset that people can swap out. 

Thoughts @chrisantonellis?

**Comment by BWPanda** [comment]
This works for me, though I applied the changes manually to the 'dev' branch, as it seems to be the most up-to-date.

Regarding the play icon, as it's just being applied via CSS, I'd say that's pretty easy to customise. For example, here's how I'm customising it to display the word 'GIF' in a semi-transparent circle/button:

```css
.ff-container .ff-playpause {
  background: none;
  background: rgba(0, 0, 0, 0.75);
  border-radius: 30px;
  color: #fff;
  font-size: 20px;
  font-weight: bold;
  height: 60px;
  left: 50%;
  line-height: 60px;
  margin: -30px 0 0 -30px;
  text-align: center;
  text-transform: uppercase;
  top: 50%;
  width: 60px;
}

.ff-container .ff-playpause:after {
  content: 'gif';
}

.ff-container:hover .ff-playpause {
  background: rgba(0, 0, 0, 0.5);
}
```

**Comment by chrisantonellis** [comment]
I just merged this into dev, I need to make a few changes before merging into master. I'll comment here with the changes i've made. 

@nickforddesign I agree, this change needs to be made for any Base64 images in the SCSS

@pweigand @BWPanda Thanks for your contributions!

**Comment by sido420** [comment]
any updates on this?

**Comment by nickforddesign** [comment]
Sorry this took so long to address, we've merged this feature after fixing some small issues.

Thanks again to @pweigand!

**Pull request merged**
